name: se_project02
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.5.6
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.4+9
  firebase_core_web: ^0.1.1
  flutter_form_builder: ^3.14.0
  font_awesome_flutter: ^8.10.0
  get: ^3.15.0
  uuid: ^2.2.2
  auto_route: ^0.6.9
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  fluttertoast: ^7.1.1
  webview_flutter: ^0.3.19+9
  cached_network_image: ^2.0.0
  http: ^0.12.0+4
  firebase_helpers: ^0.1.5
  table_calendar: ^2.2.3
  carousel_slider: ^2.3.1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  pedometer: ^0.0.5
  percent_indicator: ^2.1.8
  flutter_launcher_icons: ^0.8.0
  decimal: ^0.3.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  auto_route_generator: ^0.6.8
  build_resolvers: 1.3.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/step.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/admin.jpeg
    - assets/1_med.jpg
    - assets/2_med.jpg
    - assets/3_med.jpg
    - assets/4_med.jpg
    - assets/background.jpg
    - assets/chat-jych-0a14cabfaef5.json
    - assets/bot.png
    - assets/user.png
    - assets/heart.jpg
    - assets/distance.png
    - assets/water.png
    - assets/step.png
    - assets/step.png
    - assets/burned.png
    - assets/barras.png
    - assets/corona.jpg
    - assets/cor.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
